 if ( NOT ANDROID_ABI OR NOT CMAKE_BUILD_TYPE )
     return()
 endif()
 if(${ANDROID_ABI} STREQUAL "x86_64")
     include("android-project/app/build/build/x86_64/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
 elseif(${ANDROID_ABI} STREQUAL "x86")
     include("android-project/app/build/build/x86/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
 elseif(${ANDROID_ABI} STREQUAL "arm64-v8a")
     include("android-project/app/build/build/armv8/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
 elseif(${ANDROID_ABI} STREQUAL "armeabi-v7a")
     include("android-project/app/build/build/armv7/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
 else()
     message(FATAL "Not supported configuration")
 endif()
